### ISSUE TITLE
Split into `gradle-dist` and `gradle-run`

### ISSUE THREAD

**Issue by AidanDelaney** [paketo-buildpacks/gradle#295]
As a platform provider I want to use gradle to run some pre-build and post-build steps.  It is important that my pre-/post-build steps are factored out as separate `gradle` invocations as each invocation is run with different parameters.

## Describe the Enhancement
The `gradle` buildpack performs two steps to provide a build-time `gradle` binary.  These are

* Requests that a JDK be installed
* Links the ~/.gradle to a layer for caching

The provision of `gradle` could be handled by a `gradle-dist` buildpack

The other steps would then be handled by a `gradle-run` buildpack.

## Possible Solution
I would like to know if splitting the buildpack makes any sense.

The existing `gradle` buildpack would become a meta-buildpack.  The components of which could then be re-sequenced by platform providers in their own custom build orders.

## Motivation
A real world use-case would use `gradle-dist` to provide a `gradle` binary.  Then a pre-build step would validate properties about any provided `gradlew` file before a subsequent `gradle-run`.

**Comment by dmikusa** [comment]
I'm not sure I follow your use case. It sounds like you want to run gradle multiple times?

Can you expand or maybe provide an example of what you're wanting to do? I'd like to focus on the use case before we talk about how best to do that.

**Comment by aelfric** [comment]
What we would like to be able to do is add a layer that supplies it's own gradle wrapper.  In order for that to be possible, we need to run `gradle wrapper --distributionUrl=...` which means we need the gradle distribution and then we want to run the application build phase using the gradle wrapper that the separate layer contributed.

**Comment by dmikusa** [comment]
Hmm, ok. That's a little different than what we typically get, where users provide the gradle wrapper.

So does this sum up the workflow:

1. Install gradle
2. Run command to add gradle wrapper
3. Run build with gradle wrapper

As compared to what we do presently:

1. User provides gradle wrapper with the app
2. Run build with gradle wrapper

I can say I personally have no interest in splitting the buildpack up. The Java buildpacks mirror the technologies that we support, and breaking them down more complicates things. It would also present a big migration challenge in terms of how we'd go from what we have now to more buildpacks. 

I'll let my other @paketo-buildpacks/java-maintainers chime in with their thoughts too.

What we can do now is this:

1. Install the latest gradle
2. Use a grade wrapper if it exists
3. Run gradle commands

Without too much fuss, we could add support to install an arbitrary Gradle version. Like if you fed in the distribution URL, we could install that version of Gradle. The only caveat is that it would require Internet access, but then so would using the grade command to install the wrapper.

If we did that, then you could perhaps simplify things to:

1. Install specific gradle
2. Run build with gradle

That is assuming the whole exercise of installing the Gradle wrapper is so that you can get the specific version of Gradle you need to run your project. If that's not a valid assumption, let me know.

**Comment by aelfric** [comment]
In a perfect world what we want to do is: extract the distribution URL from the gradle wrapper properties file that is present in the project if one is present, validate it against our trusted list of distributions, and if it is trusted, then pass that distributionUrl onto the gradle buildpack for installation.  And, in cases where no gradle wrapper properties file is present, then we are content with using the default gradle distribution provided by the buildpack.

**Comment by dmikusa** [comment]
Gotcha. Yes, I think you could do exactly that with a custom buildpack.

You can add it to the list of buildpacks somewhere before the gradle buildpack. The detect script could look for `build.gradle` (or some other clues) and if present read the distribution URL. If it's in the approved list, pass detection. If it's not fail detection. That would prevent builds and fail early.

Your build process would probably be able to do nothing, cause it would only run if detect passes and if it passes the distribution URL would already be OK. Then the standard gradle buildpack would run and do its thing.

**Comment by aelfric** [comment]
I think we can close this issue. In our case, we will add a layer that runs before this layer to generate a new gradle wrapper installation with the desired distribution. Then this layer can proceed normally with no changes required.
